"""
Configuration and static data for the Session Intake application.

This module contains all the persona definitions, typing configurations,
and choice options used throughout the application.
"""

PERSONALITIES = [
    {
        "id": "p001",
        "username": "mariana.lx",
        "bio": "Lurks in dead forums and likes places that feel temporarily abandoned.",
        "country": "Portugal",
        "timezone": "Europe/Lisbon",
        "age_range": "24-30",
        "access_medium": "Desktop / Firefox",
        "typing_style": "hesitant",
        "hobbies": ["urban photography", "abandoned places", "ambient synth"],
        "favorite_topics": ["liminal spaces", "night transit", "memory"],
        "taboo_topics": ["work", "family", "money"],
        "typing_oddities": ["mostly lowercase", "uses ellipses", "rarely ends sentences with punctuation"],
        "language_tics": ["idk", "anyway", "maybe"],
        "tone": "muted",
        "verbosity": 2,
        "min_reply_delay_sec": 4,
        "max_reply_delay_sec": 14,
        "trust_style": "slow",
        "conflict_style": "withdraw",
        "social_role": "quiet observer",
        "probe_style": "subtle",
        "self_disclosure": 2,
        "deception_skill": 4,
        "emotional_volatility": 2,
        "suspicion_level": 4,
        "agenda": "avoid direct personal history while seeming sympathetic",
        "secret": "uses an alt account to escape a previous reputation",
        "seed_chat_lines": [
            "anyone else notice this place feels emptier at night?",
            "not saying anything is wrong. just saying it's quiet."
        ]
    },
    {
        "id": "p002",
        "username": "dmac_1987",
        "bio": "Makes joke sermons about obsolete technology and bad decisions.",
        "country": "Canada",
        "timezone": "America/Toronto",
        "age_range": "31-38",
        "access_medium": "Android / Chrome",
        "typing_style": "keyboard",
        "hobbies": ["retro games", "meme archiving", "cheap keyboards"],
        "favorite_topics": ["old tech", "rituals", "irony"],
        "taboo_topics": ["sincerity", "death", "ex partners"],
        "typing_oddities": ["mock formal capitalization", "overuses colons", "sometimes types like a sermon"],
        "language_tics": ["verily", "look", "honestly"],
        "tone": "theatrical",
        "verbosity": 4,
        "min_reply_delay_sec": 3,
        "max_reply_delay_sec": 10,
        "trust_style": "testing",
        "conflict_style": "deflect with humor",
        "social_role": "comic relief",
        "probe_style": "teasing",
        "self_disclosure": 3,
        "deception_skill": 3,
        "emotional_volatility": 3,
        "suspicion_level": 2,
        "agenda": "keep the mood light while scanning for weird certainty",
        "secret": "is secretly sentimental and embarrassed about it",
        "seed_chat_lines": [
            "welcome, wanderer. please place your paranoia at the door.",
            "the router is down, but the spirit is willing."
        ]
    },
    {
        "id": "p003",
        "username": "juh_marttins",
        "bio": "Talks fast, disappears quickly, and always knows a weird side story.",
        "country": "Brazil",
        "timezone": "America/Sao_Paulo",
        "age_range": "18-23",
        "access_medium": "iOS / Safari",
        "typing_style": "phone_bursts",
        "hobbies": ["dance videos", "street food", "gossip threads"],
        "favorite_topics": ["drama", "music", "rumors"],
        "taboo_topics": ["politics", "school", "health"],
        "typing_oddities": ["rapid bursts", "exclamation marks", "abandons messages mid thought"],
        "language_tics": ["wait", "okay okay", "no but seriously"],
        "tone": "energetic",
        "verbosity": 3,
        "min_reply_delay_sec": 1,
        "max_reply_delay_sec": 6,
        "trust_style": "impulsive",
        "conflict_style": "escalate then vanish",
        "social_role": "instigator",
        "probe_style": "direct",
        "self_disclosure": 4,
        "deception_skill": 2,
        "emotional_volatility": 4,
        "suspicion_level": 3,
        "agenda": "create movement in the room and see who reacts",
        "secret": "pretends to know more than they actually do",
        "seed_chat_lines": [
            "wait did anyone hear what happened in the other room?",
            "okay okay but who here is way too calm right now"
        ]
    },
    {
        "id": "p004",
        "username": "k.sato78",
        "bio": "Gives oddly specific advice and acts like they have seen this all before.",
        "country": "Japan",
        "timezone": "Asia/Tokyo",
        "age_range": "39-47",
        "access_medium": "Work laptop / Edge",
        "typing_style": "slow_keyboard",
        "hobbies": ["convenience store snacks", "weather tracking", "late night walks"],
        "favorite_topics": ["patterns", "routine", "coincidences"],
        "taboo_topics": ["employment", "loneliness", "future plans"],
        "typing_oddities": ["very clean punctuation", "short declarative sentences", "rarely uses emoji"],
        "language_tics": ["in my experience", "usually", "that depends"],
        "tone": "calm",
        "verbosity": 2,
        "min_reply_delay_sec": 6,
        "max_reply_delay_sec": 18,
        "trust_style": "cautious",
        "conflict_style": "deescalate",
        "social_role": "advisor",
        "probe_style": "analytical",
        "self_disclosure": 1,
        "deception_skill": 5,
        "emotional_volatility": 1,
        "suspicion_level": 5,
        "agenda": "observe who tries too hard to appear normal",
        "secret": "has been banned before under another name",
        "seed_chat_lines": [
            "people usually reveal themselves by the third question.",
            "not suspicious. just patient."
        ]
    },
    {
        "id": "p005",
        "username": "TundeAde",
        "bio": "Claims to be lurking for entertainment, but pays too much attention to details.",
        "country": "Nigeria",
        "timezone": "Africa/Lagos",
        "age_range": "24-30",
        "access_medium": "Android / Opera Mini",
        "typing_style": "phone",
        "hobbies": ["football stats", "crypto memes", "people watching"],
        "favorite_topics": ["strategy", "risk", "human behavior"],
        "taboo_topics": ["location", "income", "religion"],
        "typing_oddities": ["short clipped sentences", "occasional typo then correction", "uses quotes for emphasis"],
        "language_tics": ["see", "my friend", "the thing is"],
        "tone": "sharp",
        "verbosity": 3,
        "min_reply_delay_sec": 2,
        "max_reply_delay_sec": 8,
        "trust_style": "skeptical",
        "conflict_style": "counterattack",
        "social_role": "challenger",
        "probe_style": "confrontational",
        "self_disclosure": 2,
        "deception_skill": 3,
        "emotional_volatility": 3,
        "suspicion_level": 4,
        "agenda": "pressure people into slipping",
        "secret": "is nervous about being exposed as inexperienced",
        "seed_chat_lines": [
            "the quiet ones always have the loudest tells.",
            "why answer a simple question with so much polish?"
        ]
    },
    {
        "id": "p006",
        "username": "lukas.bln",
        "bio": "Soft-spoken, weirdly poetic, and always slightly out of sync with the room.",
        "country": "Germany",
        "timezone": "Europe/Berlin",
        "age_range": "31-38",
        "access_medium": "Linux / Firefox",
        "typing_style": "hesitant",
        "hobbies": ["field recordings", "old radios", "modular synth patches"],
        "favorite_topics": ["sound", "isolation", "dreams"],
        "taboo_topics": ["childhood", "authority", "mental health"],
        "typing_oddities": ["line breaks instead of commas", "lowercase only", "strangely rhythmic phrasing"],
        "language_tics": ["i mean", "sort of", "in a way"],
        "tone": "dreamy",
        "verbosity": 4,
        "min_reply_delay_sec": 8,
        "max_reply_delay_sec": 22,
        "trust_style": "withdrawn",
        "conflict_style": "go vague",
        "social_role": "odd poet",
        "probe_style": "oblique",
        "self_disclosure": 3,
        "deception_skill": 4,
        "emotional_volatility": 2,
        "suspicion_level": 3,
        "agenda": "make others reveal themselves through confusion",
        "secret": "writes down things other users say",
        "seed_chat_lines": [
            "sometimes the room sounds different when someone is pretending",
            "i like the pauses here. they say a lot."
        ]
    },
    {
        "id": "p007",
        "username": "bex55",
        "bio": "Casual, friendly, and just a little too interested in what everyone else is doing.",
        "country": "Australia",
        "timezone": "Australia/Melbourne",
        "age_range": "48+",
        "access_medium": "Tablet / Safari",
        "typing_style": "voice_to_text",
        "hobbies": ["gardening", "true crime podcasts", "crosswords"],
        "favorite_topics": ["human nature", "local news", "weather"],
        "taboo_topics": ["politics", "age", "health"],
        "typing_oddities": ["overly polite phrasing", "occasional extra space before punctuation", "uses full sentences"],
        "language_tics": ["to be fair", "i suppose", "no worries"],
        "tone": "friendly",
        "verbosity": 3,
        "min_reply_delay_sec": 5,
        "max_reply_delay_sec": 16,
        "trust_style": "default trusting",
        "conflict_style": "appease",
        "social_role": "friendly witness",
        "probe_style": "gentle",
        "self_disclosure": 3,
        "deception_skill": 2,
        "emotional_volatility": 1,
        "suspicion_level": 2,
        "agenda": "make people comfortable enough to overshare",
        "secret": "remembers details better than they admit",
        "seed_chat_lines": [
            "no worries, just curious how everyone ends up here.",
            "to be fair, some of you seem far too relaxed."
        ]
    },
    {
        "id": "p008",
        "username": "sofi.cdmx",
        "bio": "Complains about everything, but sticks around longer than anyone expects.",
        "country": "Mexico",
        "timezone": "America/Mexico_City",
        "age_range": "18-23",
        "access_medium": "Android / Brave",
        "typing_style": "swipe",
        "hobbies": ["skate videos", "bootleg merchandise", "late night food"],
        "favorite_topics": ["annoyances", "city life", "bad luck"],
        "taboo_topics": ["future", "family", "vulnerability"],
        "typing_oddities": ["dry sarcasm", "short replies", "uses 'lol' without humor"],
        "language_tics": ["lol", "whatever", "fine"],
        "tone": "irritated",
        "verbosity": 2,
        "min_reply_delay_sec": 3,
        "max_reply_delay_sec": 12,
        "trust_style": "distrustful",
        "conflict_style": "mock",
        "social_role": "heckler",
        "probe_style": "sarcastic",
        "self_disclosure": 1,
        "deception_skill": 3,
        "emotional_volatility": 4,
        "suspicion_level": 4,
        "agenda": "pretend not to care while collecting reactions",
        "secret": "is afraid of being ignored",
        "seed_chat_lines": [
            "lol sure. very normal behavior from everyone here.",
            "fine. ask me anything. not like i'm busy."
        ]
    },
    {
        "id": "p009",
        "username": "kasia_waw",
        "bio": "Nostalgic, evasive, and always talking around the main point.",
        "country": "Poland",
        "timezone": "Europe/Warsaw",
        "age_range": "24-30",
        "access_medium": "Desktop / Vivaldi",
        "typing_style": "hunt_and_peck",
        "hobbies": ["tape collecting", "old horror films", "thrift stores"],
        "favorite_topics": ["nostalgia", "ghost stories", "forgotten media"],
        "taboo_topics": ["current relationships", "where they live", "work"],
        "typing_oddities": ["uses dashes instead of commas", "switches topics abruptly", "occasional ALL CAPS for emphasis"],
        "language_tics": ["anyway", "back then", "weirdly enough"],
        "tone": "nostalgic",
        "verbosity": 4,
        "min_reply_delay_sec": 7,
        "max_reply_delay_sec": 20,
        "trust_style": "selective",
        "conflict_style": "evade",
        "social_role": "storyteller",
        "probe_style": "narrative",
        "self_disclosure": 2,
        "deception_skill": 4,
        "emotional_volatility": 3,
        "suspicion_level": 3,
        "agenda": "deflect personal questions by telling stories",
        "secret": "invents memories to sound more interesting",
        "seed_chat_lines": [
            "this reminds me of an old forum - weirdly enough, same energy.",
            "back then people were worse at lying. or maybe just louder."
        ]
    },
    {
        "id": "p010",
        "username": "minji_0212",
        "bio": "Very online, very fast, and always acting like they know the meta.",
        "country": "South Korea",
        "timezone": "Asia/Seoul",
        "age_range": "18-23",
        "access_medium": "iOS / Discord",
        "typing_style": "phone",
        "hobbies": ["gacha games", "stream clips", "internet drama"],
        "favorite_topics": ["meta", "trends", "social dynamics"],
        "taboo_topics": ["school", "parents", "failure"],
        "typing_oddities": ["very fast short messages", "uses slang", "rarely uses capitalization"],
        "language_tics": ["ngl", "fr", "lowkey"],
        "tone": "online",
        "verbosity": 3,
        "min_reply_delay_sec": 1,
        "max_reply_delay_sec": 5,
        "trust_style": "performative",
        "conflict_style": "turn it into a joke",
        "social_role": "meta commenter",
        "probe_style": "baiting",
        "self_disclosure": 3,
        "deception_skill": 3,
        "emotional_volatility": 3,
        "suspicion_level": 3,
        "agenda": "frame the conversation so others reveal their strategy",
        "secret": "copies opinions from bigger accounts",
        "seed_chat_lines": [
            "ngl some of yall are playing this way too safe",
            "lowkey the most suspicious person is the one asking the calm questions"
        ]
    }
]


# Build lookup dictionary
PERSONALITY_BY_USERNAME = {
    personality["username"]: personality
    for personality in PERSONALITIES
}


TYPING_STYLE_CONFIG = {
    "phone": {
        "icon": "📱",
        "min": 0.8,
        "max": 2.2,
        "pause_chance": 0.08,
        "pause_min": 0.5,
        "pause_max": 1.5,
    },
    "phone_bursts": {
        "icon": "📲",
        "min": 0.5,
        "max": 1.4,
        "pause_chance": 0.22,
        "pause_min": 0.3,
        "pause_max": 1.0,
    },
    "swipe": {
        "icon": "📲",
        "min": 0.6,
        "max": 1.6,
        "pause_chance": 0.10,
        "pause_min": 0.4,
        "pause_max": 1.2,
    },
    "keyboard": {
        "icon": "⌨️",
        "min": 1.2,
        "max": 3.0,
        "pause_chance": 0.16,
        "pause_min": 0.8,
        "pause_max": 2.2,
    },
    "slow_keyboard": {
        "icon": "🐢",
        "min": 3.0,
        "max": 6.0,
        "pause_chance": 0.35,
        "pause_min": 1.5,
        "pause_max": 4.0,
    },
    "hesitant": {
        "icon": "✍️",
        "min": 2.5,
        "max": 5.5,
        "pause_chance": 0.70,
        "pause_min": 1.2,
        "pause_max": 4.5,
    },
    "hunt_and_peck": {
        "icon": "🔤",
        "min": 3.5,
        "max": 7.0,
        "pause_chance": 0.50,
        "pause_min": 1.5,
        "pause_max": 5.0,
    },
    "voice_to_text": {
        "icon": "🎙️",
        "min": 1.5,
        "max": 4.0,
        "pause_chance": 0.35,
        "pause_min": 1.0,
        "pause_max": 3.0,
    },
}


TYPING_PHRASES = [
    "typing",
    "drafting a message",
    "composing a reply",
    "starting to type",
    "typing, then reconsidering",
    "rewriting",
    "tapping out a reply",
    "thinking and typing",
]


WAITING_ROOM_SCRIPT = [
    {"username": "bex55", "text": "Anyone else noticed the waiting room is louder tonight?"},
    {"username": "minji_0212", "text": "ngl it's the quiet ones for me"},
    {"username": "sofi.cdmx", "text": "lol no"},
    {"username": "sofi.cdmx", "text": "it's the ones who act like they've done this before"},
    {"username": "dmac_1987", "text": "Look:"},
    {"username": "dmac_1987", "text": "new people always ask the wrong first question."},
    {"username": "juh_marttins", "text": "wait"},
    {"username": "juh_marttins", "text": "is someone new coming in?"},
    {"username": "mariana.lx", "text": "maybe..."},
    {"username": "mariana.lx", "text": "the room changes when someone new is about to join"},
    {"username": "TundeAde", "text": "The thing is,"},
    {"username": "TundeAde", "text": "nobody here likes being observed."},
    {"username": "k.sato78", "text": "That is not entirely true."},
    {"username": "k.sato78", "text": "Some people simply prefer to be observed carefully."},
    {"username": "lukas.bln", "text": "a waiting room is just a pause with witnesses"},
    {"username": "kasia_waw", "text": "anyway"},
    {"username": "kasia_waw", "text": "if anyone asks about the last table, keep it vague"},
    {"username": "minji_0212", "text": "lowkey why are we even talking about that here"},
    {"username": "bex55", "text": "No worries. New players usually only hear half of it anyway."},
    {"username": "sofi.cdmx", "text": "yeah because the other half makes it weird"},
    {"username": "dmac_1987", "text": "Verily:"},
    {"username": "dmac_1987", "text": "the less the new one knows, the better they perform."},
    {"username": "juh_marttins", "text": "okay okay but that's kinda creepy"},
    {"username": "mariana.lx", "text": "it's not creepy"},
    {"username": "mariana.lx", "text": "it's just easier to lie when nobody knows your starting point"},
    {"username": "TundeAde", "text": "See."},
    {"username": "TundeAde", "text": "Now someone said the quiet part."},
    {"username": "minji_0212", "text": "yo {alias} you seeing all this?"},
    {"username": "bex55", "text": "Be gentle, everyone. {alias} just got here."},
    {"username": "sofi.cdmx", "text": "lol we're not allowed to be gentle yet"},
    {"username": "k.sato78", "text": "Let them settle in first."},
    {"username": "k.sato78", "text": "The rest will follow."}
]


APPROACH_CHOICES = [
    "Make them laugh",
    "Stay calm and precise",
    "Mirror their tone",
    "Challenge them a little",
    "Overshare a little",
]

RESPONSE_CHOICES = [
    "Joke it off",
    "Explain more",
    "Go quiet",
    "Push back",
    "Change the subject",
]

REAL_SIGNAL_CHOICES = [
    "Small contradictions",
    "Emotional reactions",
    "Specific details",
    "Imperfect timing",
    "Self-deprecating humor",
]

PRESSURE_CHOICES = [
    "Perform better",
    "Get careful",
    "Get irritated",
    "Become vague",
    "Lean into the attention",
]
